@startuml states

!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

[*] --> TitleState
TitleState --> MenuState
MenuState --> [*]
MenuState --> LoadingState
MenuState --> SettingsState
SettingsState --> MenuState
LoadingState --> GameState
GameState --> PauseState
GameState --> GameOverState
GameOverState --> MenuState
PauseState --> GameState
PauseState --> MenuState

@enduml