@startuml states

!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

[*] --> TitleState
TitleState --> LoadingState
LoadingState --> MenuState
MenuState --> [*]
MenuState --> GameState
MenuState --> SettingsState
SettingsState --> MenuState
GameState --> PauseState
PauseState --> GameState
PauseState --> MenuState

@enduml